apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: kafka
  labels:
    app: spark
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: spark-image:latest  #
