apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion-container
          image: sinasedghi/ingestion
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: FLASK_APP
              value: "ingestion.py"
            - name: FLASK_ENV
              value: "production"
            - name: KAFKA_SERVER
              value: "kafka.kafka.svc.cluster.local:9092"  # Address of Kafka service
            - name: KAFKA_TOPIC
              value: "dataTopic"   # Kafka topic name
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: kafka
spec:
  type: LoadBalancer
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

