apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator-deployment
  namespace: kafka  # اضافه کردن این خط
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: generator-container
          image: erfanerfan/generator
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

